agents:
  queue: central

steps:
  - label: "hello"
    command:
      - echo "Hello world"
      - buildkite-agent meta-data set "testkey" "my job is $$BUILDKITE_JOB_ID"

  - wait
  
  - label: "follow"
    command:
      - buildkite-agent meta-data get "testkey" --job "$$BUILDKITE_JOB_ID"
      - buildkite-agent meta-data get "testkey" --job "$$BUILDKITE_STEP_ID"
      - buildkite-agent meta-data get "testkey" --job "$$BUILDKITE_BUILD_ID"
      - buildkite-agent meta-data get "testkey" --job "0183aa8f-226a-4c63-b35d-21a12cbbc4f2"
