agents:
  queue: test
steps:


  - label: "Test on clima"
    command:
      - julia --project=.buildkite -e 'using Pkg; Pkg.instantiate()'
      - srun nsys profile --trace=nvtx,cuda,mpi --output=report_%q{PMI_RANK} --force-overwrite true julia --project=.buildkite .buildkite/test_cuda_mpi.jl
      - nsys stats --report cuda_gpu_trace report_0.nsys-rep --force-export true
      - nsys stats --report cuda_gpu_trace report_0.nsys-rep --force-export true | grep -E "memcpy (Peer-to-Peer|PtoP)"
    agents:
      slurm_queue: invalid
      slurm_ntasks: 2
      slurm_gpus_per_task: 1
      slurm_cpus_per_task: 4
      slurm_time: "00:10:00"
      modules: climacommon/2024_10_09

