agents:
  queue: central
  modules: julia/1.8.5 openmpi/4.1.4 nsight-systems/2022.2.1

steps:

  - label: "instantiate Julia projects"
    key: "init"
    command:
      - julia --project=.ci -e 'using Pkg; Pkg.instantiate()'
      - julia --project=utils -e 'using Pkg; Pkg.instantiate()'

  - wait

  - label: "Print only rank 0"
    key: "print"
    command:
      - ": > print-out-0 && tail -f print-out-0 &"
      - srun --output=print-out-%t printenv PMI_RANK
      - kill %1
    agents:
      slurm_ntasks_per_node: 2
      slurm_nodes: 2
      slurm_time: 00:05:00
    artifact_paths:
      - "print-out-*"

  - label: "HDF5 memory profile"
    key: "hdf5-mem-profile"
    command:
      - srun --profile=task --acctg-freq=10 julia -e 'X = ones(UInt8, 1024^3); sleep(60); println(sum(X))' # allocate 1GB
      - sh5util -j $$SLURM_JOB_ID
      - sh5util -j $$SLURM_JOB_ID -E --series=Tasks -l Node:TimeSeries
    artifact_paths:
      - "job_*.h5"
      - "extract_*.csv"
    agents:
      slurm_ntasks_per_node: 3
      slurm_mem_per_cpu: 4G
      slurm_time: 00:05:00


  - label: "Nsight - single node profile"
    key: "nsys-single"
    command:
      - nsys profile --output=report-single --trace=mpi --mpi-impl=openmpi srun julia --project=.ci .ci/mpi.jl
    artifact_paths:
      - "report-single.nsys-rep"
    agents:
      slurm_ntasks_per_node: 3
      slurm_time: 00:05:00

  - label: "Nsight - multi node profile"
    key: "nsys-multi"
    command:
      - srun --cpu-bind=cores nsys profile --output=report-multi-%q{PMI_RANK} --trace=mpi --mpi-impl=openmpi julia --project=.ci .ci/mpi.jl
    artifact_paths:
      - "report-multi-*.nsys-rep"
    agents:
      slurm_cpus_per_task: 2
      slurm_ntasks_per_node: 2
      slurm_nodes: 2
      slurm_time: 00:05:00
