agents:
  queue: clima
steps:

  - group: "CUDA/MPI Tests"
    key: "cuda-mpi-tests"
    steps:
      - label: "RunPod smoke test"
        command:
          - nvidia-smi
          - julia -e 'println("hello from runpod")'
        agents:
          queue: runpod
          runpod_gpus: 1
