agents:
  queue: clima
steps:

  - group: "CUDA/MPI Tests"
    key: "cuda-mpi-tests"
    steps:
      - label: "CUDA/MPI test on derecho"
        command:
          - julia --project=.buildkite -e 'using Pkg; Pkg.instantiate()'
          - mpiwrapperexec -n 2 set_gpu_rank nsys profile --trace=nvtx,cuda,mpi --output=report_%q{PMI_RANK} --force-overwrite true julia --project=.buildkite .buildkite/test_cuda_mpi.jl
          - nsys stats --report cuda_gpu_trace report_0.nsys-rep --force-export true
          - nsys stats --report cuda_gpu_trace report_0.nsys-rep --force-export true | grep -E "memcpy (Peer-to-Peer|PtoP)"
        agents:
          queue: derecho
          pbs_l_select: "1:ngpus=2:ncpus=64"
          pbs_l_walltime: "00:10:00"
          pbs_q: develop
          modules: climacommon/2025_02_25

      - label: "CUDA/MPI test on clima"
        command:
          - julia --project=.buildkite -e 'using Pkg; Pkg.instantiate()'
          - srun nsys profile --trace=nvtx,cuda,mpi --output=report_%q{PMI_RANK} --force-overwrite true julia --project=.buildkite .buildkite/test_cuda_mpi.jl
          - nsys stats --report cuda_gpu_trace report_0.nsys-rep --force-export true
          - nsys stats --report cuda_gpu_trace report_0.nsys-rep --force-export true | grep -E "memcpy (Peer-to-Peer|PtoP)"
        agents:
          queue: clima
          slurm_ntasks: 2
          slurm_gpus_per_task: 1
          slurm_cpus_per_task: 4
          slurm_time: "00:10:00"
          modules: climacommon/2024_10_09

      - label: "CUDA/MPI test on central"
        command:
          - julia --project=.buildkite -e 'using Pkg; Pkg.instantiate()'
          # Using srun crashes upon MPI.jl initialization
          - mpirun -n 2 nsys profile --trace=cuda,mpi --mpi-impl=openmpi --force-overwrite true julia --project=.buildkite .buildkite/test_cuda_mpi.jl
          - nsys stats --report cuda_gpu_trace report1.nsys-rep --force-export true
          - nsys stats --report cuda_gpu_trace report1.nsys-rep --force-export true | grep -E "memcpy (Peer-to-Peer|PtoP)"
        agents:
          queue: central
          slurm_ntasks: 2
          slurm_gpus_per_task: 1
          slurm_cpus_per_task: 4
          slurm_time: "00:10:00"
          modules: climacommon/2024_10_09
        soft_fail: true

      - label: "CUDA/MPI test on GCP"
        command:
          - julia --project=.buildkite -e 'using Pkg; Pkg.instantiate()'
          - mpiexec -n 2 nsys profile --trace=cuda,mpi --mpi-impl=openmpi --force-overwrite true julia --project=.buildkite .buildkite/test_cuda_mpi.jl
          - nsys stats --report cuda_gpu_trace report1.nsys-rep --force-export true
          - nsys stats --report cuda_gpu_trace report1.nsys-rep --force-export true | grep -E "memcpy (Peer-to-Peer|PtoP)"
        agents:
          queue: gcp
          slurm_ntasks: 2
          slurm_gpus: 2
          slurm_cpus_per_task: 4
          slurm_time: "00:10:00"
        soft_fail: true

  - group: "rqrun Tests"
    key: "rqrun-tests"
    steps:
      - label: "rqrun test on derecho"
        command:
          - julia .buildkite/test_rqrun_simple.jl
        agents:
          queue: derecho
          pbs_q: develop
          pbs_l_select: "1:ncpus=1"
          modules: climacommon/2025_02_25

      - label: "rqrun test on clima"
        command:
          - julia .buildkite/test_rqrun_simple.jl
        agents:
          queue: clima
          modules: climacommon/2024_10_09

