agents:
  queue: central
  modules: mpich/4.0.0 julia/1.8.3

steps:
  - label: "hello"
    command:
      - julia -e 'println("hello world")'
  - label: "hello 2"
    command:
      - julia -e 'println("hello world")'
    agents:
      slurm_mem: 2G
