agents:
  queue: central

steps:
  - label: "hello"
    command:
      - echo "Hello world"
      - buildkite-agent meta-data set "testkey" "my job is $$BUILDKITE_JOB_ID"

  - wait
  
  - label: "follow"
    command:
      - buildkite-agent meta-data get "testkey" --job "$$BUILDKITE_JOB_ID"
      - echo "old"
      - buildkite-agent meta-data get "testkey" --job "0183aa97-cb68-405b-a3d3-df342ce7c7aa"
