#!/bin/bash
# Prefetch CliMA Julia artifacts into /clima-artifacts so that Pkg.instantiate
# resolves them on disk and never hits the network at job time.
#
# Launched in the background at container start by start.sh, overlapping its
# work with agent registration, job acquisition, and git checkout. The
# pre-command hook blocks on /clima-artifacts/.ready before any Julia step.
#
# Driven by /etc/clima-artifacts.tsv, one line per artifact:
#
#   # comments and blank lines ignored
#   <name>\t<git-tree-sha1>\t<url>
#
# The `name` column is informational; this script keys by `git-tree-sha1`
# and trusts HTTPS+R2 for transport integrity (tar -xz fails if a tarball
# is corrupted, which is caught via pipefail).
#
# Optional filtering via env vars:
#   CLIMA_ARTIFACTS           comma-separated artifact NAMES to prefetch
#   CLIMA_ARTIFACTS_PROJECTS  comma-separated project names (e.g. ClimaLand,ClimaAtmos);
#                             Artifacts.toml is fetched from GitHub raw for each
#                             and its artifact names are added to the prefetch set.
# If either is set, prefetch is restricted to the union. If both are unset,
# the full manifest is prefetched (current default).
#
# Per artifact: stream curl → tar -xz into a staging dir on the same fs as
# the target, atomically rename into /clima-artifacts/artifacts/<hash>/.
# After all succeed, writes Overrides.toml and touches .ready; on any failure
# touches .failed.

set -uo pipefail

MANIFEST=/etc/clima-artifacts.tsv
DEPOT=/clima-artifacts
ART_DIR="$DEPOT/artifacts"
PARALLEL=4

log() { printf '[clima-artifacts] %(%H:%M:%S)T %s\n' -1 "$*"; }

mkdir -p "$ART_DIR"
rm -f "$DEPOT/.ready"
# Reap any orphan staging dirs left behind by a previous run that was killed
# mid-extract (e.g. pod stop while a tarball was unpacking). Without this they
# accumulate on the volume disk across stop/resume cycles.
find "$ART_DIR" -maxdepth 1 -mindepth 1 -name 'tmp.*' -type d -exec rm -rf {} + 2>/dev/null || true

# Truncate-and-init the Overrides.toml. fetch_one appends to it under flock
# as each artifact lands, so partial-prefetch leaves a valid file for Julia.
echo "# Auto-generated by install-clima-artifacts.sh — do not edit by hand" \
    > "$ART_DIR/Overrides.toml"

if [ ! -f "$MANIFEST" ]; then
    log "manifest not found at $MANIFEST — nothing to do"
    touch "$DEPOT/.ready"
    exit 0
fi

append_override() {
    local name="$1" hash="$2"
    (
        flock -x 200
        printf '# %s\n%s = "%s"\n' "$name" "$hash" "$ART_DIR/$hash" \
            >> "$ART_DIR/Overrides.toml"
    ) 200>"$DEPOT/.overrides.lock"
}

fetch_one() {
    local name="$1" hash="$2" url="$3"
    local dest="$ART_DIR/$hash"
    local marker="$dest/.complete"

    if [ -f "$marker" ]; then
        log "skip $name (already present)"
        append_override "$name" "$hash"
        return 0
    fi

    local tmp stage
    tmp="$(mktemp -d -p "$ART_DIR")"
    stage="$tmp/extract"
    mkdir -p "$stage"

    log "fetch $name <- $url"
    # `--no-same-owner` skips trying to chown extracted files to the original
    # uid/gid (the central user) — Runpod's user namespace blocks that.
    # Without it, tar exits non-zero and pipefail fails the whole pipeline,
    # even though all files unpacked.
    if ! curl -fsSL --retry 5 --retry-delay 10 --retry-all-errors "$url" \
            | tar -xz --no-same-owner -C "$stage"; then
        log "ERR download/extract pipeline failed for $name"
        rm -rf "$tmp"
        return 1
    fi

    rm -rf "$dest"
    mv "$stage" "$dest"
    touch "$marker"
    rm -rf "$tmp"
    append_override "$name" "$hash"
    log "done $name"
}

# Build the allowed-names filter from env vars (empty = no filter).
allowed=""
if [ -n "${CLIMA_ARTIFACTS:-}" ]; then
    allowed=$(printf '%s\n' "$CLIMA_ARTIFACTS" | tr ',' '\n')
fi
if [ -n "${CLIMA_ARTIFACTS_PROJECTS:-}" ]; then
    IFS=',' read -ra _projs <<< "$CLIMA_ARTIFACTS_PROJECTS"
    for proj in "${_projs[@]}"; do
        name="${proj##*/}"
        [[ "$name" != *.jl ]] && name="${name}.jl"
        url="https://raw.githubusercontent.com/CliMA/${name}/main/Artifacts.toml"
        contents=$(curl -fsSL "$url" 2>/dev/null) || {
            log "WARN: could not fetch Artifacts.toml for $name from GitHub"
            continue
        }
        # Extract top-level table names ([foo], not [[foo]] which are arrays).
        names=$(printf '%s\n' "$contents" | grep -E '^\[[a-zA-Z][a-zA-Z0-9_.-]*\][[:space:]]*$' | tr -d '[]')
        allowed="$allowed
$names"
    done
fi
allowed=$(printf '%s\n' "$allowed" | grep -v '^[[:space:]]*$' | sort -u)
if [ -n "$allowed" ]; then
    log "filter: prefetching only $(echo "$allowed" | wc -l | tr -d ' ') named artifact(s)"
fi

# Manifest is 3 cols (name, hash, url); we keep all three for nicer logging.
# When `allowed` is non-empty, drop rows whose name (col 1) isn't in the set.
mapfile -t entries < <(awk -F'\t' -v allowed="$allowed" '
    BEGIN {
        if (allowed != "") {
            n = split(allowed, arr, "\n")
            for (i=1; i<=n; i++) ok[arr[i]] = 1
        }
    }
    /^[[:space:]]*(#|$)/ {next}
    NF >= 3 {
        if (allowed != "" && !($1 in ok)) next
        print $1"\t"$2"\t"$3
    }
' "$MANIFEST")

if [ "${#entries[@]}" -eq 0 ]; then
    log "manifest has no entries"
    touch "$DEPOT/.ready"
    exit 0
fi

# List the names up front so the log is human-readable.
names_list=$(printf '%s\n' "${entries[@]}" | cut -f1 | paste -sd, -)
log "starting prefetch of ${#entries[@]} artifact(s), up to $PARALLEL in parallel: $names_list"

declare -A pid_name
fail=0

for entry in "${entries[@]}"; do
    name="$(printf '%s' "$entry" | cut -f1)"
    hash="$(printf '%s' "$entry" | cut -f2)"
    url="$(printf '%s' "$entry" | cut -f3)"

    while [ "$(jobs -rp | wc -l)" -ge "$PARALLEL" ]; do
        sleep 0.2
    done

    fetch_one "$name" "$hash" "$url" &
    pid_name[$!]="$name"
done

for pid in "${!pid_name[@]}"; do
    if ! wait "$pid"; then
        log "FAIL ${pid_name[$pid]}"
        fail=$((fail + 1))
    fi
done

if [ "$fail" -gt 0 ]; then
    log "$fail artifact(s) failed; Overrides.toml lists successes only"
fi

touch "$DEPOT/.ready"
log "all ${#entries[@]} artifact(s) ready at $DEPOT"
