#!/bin/bash

set -euo pipefail # exit on failure or unset variable
set -v

if [ ! -d "${BUILDKITE_BUILD_CHECKOUT_PATH}/.git" ]; then
    echo "--- Init clone and checkout" 
    if [ "$BUILDKITE_COMMIT" = "HEAD" ]; then
        git clone \
            --depth=1 \
            --branch "${BUILDKITE_BRANCH}" \
            ${BUILDKITE_GIT_CLONE_FLAGS} \
            ${BUILDKITE_REPO} \
            "${BUILDKITE_BUILD_CHECKOUT_PATH}"
    else
        git clone \
            --branch "${BUILDKITE_BRANCH}" \
            ${BUILDKITE_GIT_CLONE_FLAGS} \
            ${BUILDKITE_REPO} \
            "${BUILDKITE_BUILD_CHECKOUT_PATH}"
    fi
    cd "${BUILDKITE_BUILD_CHECKOUT_PATH}"
    git checkout -f "${BUILDKITE_COMMIT}"
    # emulate https://github.com/buildkite/agent/blob/7e0166eebed5bf3cc289edae97145803429e75f9/bootstrap/bootstrap.go#L1448-L1458
    if ! buildkite-agent meta-data exists "buildkite:git:commit" ; then
        echo "Sending Git commit information to Buildkite"
        git --no-pager show HEAD -s --format=fuller --no-color -- | buildkite-agent meta-data set "buildkite:git:commit"
    fi
else
    echo "--- Using cached git repo ${BUILDKITE_BUILD_CHECKOUT_PATH}"
    cd "${BUILDKITE_BUILD_CHECKOUT_PATH}"
fi

set +v
