#!/bin/bash

# The `environment` hook will run before all other commands, and can be used
# to set up secrets, data, etc. Anything exported in hooks will be available
# to the build script.
#
# For example:
#
# export SECRET_VAR=token

set -euo pipefail # exit on failure or unset variable
#set -x  # show all the commands that are being executed

source /etc/profile.d/modules.sh

export SLURM_BUILDKITE_PATH="$(dirname "${BUILDKITE_BIN_PATH}")"
export SHARED_DEPOT="${BUILDKITE_BUILD_PATH}/shared_depot"
export GIT_SSH_COMMAND="ssh -i ${SLURM_BUILDKITE_PATH}/.ssh/id_rsa -o IdentitiesOnly=yes -o UserKnownHostsFile=${SLURM_BUILDKITE_PATH}/.ssh/known_hosts"
export CI_BUILD_DIR="${BUILDKITE_BUILD_PATH}/${BUILDKITE_PIPELINE_SLUG}/${BUILDKITE_BUILD_NUMBER}"
export BUILDKITE_BUILD_CHECKOUT_PATH="${CI_BUILD_DIR}/${BUILDKITE_PIPELINE_SLUG}"
export BUILDKITE_API_TOKEN=$(cat "${SLURM_BUILDKITE_PATH}/.buildkite_token")

export TMPDIR="/tmp/slurm-${SLURM_JOB_ID}"
srun --ntasks-per-node=1 --ntasks=${SLURM_JOB_NUM_NODES} mkdir -p "${TMPDIR}"
printenv TMPDIR

ulimit -c unlimited

# Slurm Job Info
echo "--- Slurm Job ID: ${SLURM_JOB_ID}"
scontrol show job ${SLURM_JOB_ID} --details
scontrol show node ${SLURM_JOB_NODELIST}

if $(grep -q "Red Hat" /etc/redhat-release);  then
    # We are on rhel9 nodes, we also want our modules
    export MODULEPATH="/groups/esm/modules:$MODULEPATH"

    module load git/2.39.3-gcc-11.3.1-zfr3sti
else
    # We are on the CentOS nodes
    module load git/2.26.0
fi

# this is set to avoid rare race conditions on the same node with concurrent (step) jobs
export OMPI_MCA_orte_tmpdir_base="$TMPDIR"

# From https://stackoverflow.com/a/51141872, to remove colors from modules
# (Color tags mess up the builkite log)
module_list=$(module list | sed 's/\x1B\[[0-9;]\{1,\}[A-Za-z]//g')

printf -- '--- ' && echo $module_list

if [ -n "${SLURM_GPUS_ON_NODE:-}" ]; then
    echo "--- GPUs available on ${HOSTNAME}"
    nvidia-smi -L
fi

export SLACK_TOKEN=$(cat "$BUILDKITE_PATH/.slack_token")
