#!/bin/bash

# The `environment` hook will run before all other commands, and can be used
# to set up secrets, data, etc. Anything exported in hooks will be available
# to the build script.
#
# For example:
#
# export SECRET_VAR=token

set -euo pipefail # exit on failure or unset variable
set -v

export CI_BUILD_DIR="${BUILDKITE_BUILD_PATH}/${BUILDKITE_PIPELINE_SLUG}/${BUILDKITE_BUILD_NUMBER}"

# Slurm Job Info
echo "--- Slurm Job ID: ${SLURM_JOB_ID}"

module purge

case "${BUILDKITE_AGENT_META_DATA_CONFIG}" in
    # standard configurations
    init|default)
        echo "--- init env configuration"
        export BUILDKITE_BUILD_CHECKOUT_PATH=${CI_BUILD_DIR}
        ;;

    cpu)
        echo "--- cpu env configuration"
        module load julia/${JULIA_VERSION:=1.4.2}
        module load openmpi/4.0.3 hdf5/1.10.1 netcdf-c/4.6.1
        
        export BUILDKITE_BUILD_CHECKOUT_PATH=${CI_BUILD_DIR}

        export JULIA_DEPOT_PATH="${CI_BUILD_DIR}/depot/cpu"
        export JULIA_CUDA_USE_BINARYBUILDER=false
        export JULIA_MPI_BINARY=system

        export OMPI_MCA_btl="self,tcp"
        
        export CLIMATEMACHINE_SETTINGS_OUTPUT_DIR="${CI_BUILD_DIR}/output/${BUILDKITE_STEP_KEY}"
        ;;

    cpu-test)
        echo "--- cpu test env configuration"
        module load julia/${JULIA_VERSION:=1.5.1}
        module load openmpi/4.0.4 hdf5/1.10.1 netcdf-c/4.6.1

        export BUILDKITE_BUILD_CHECKOUT_PATH=${CI_BUILD_DIR}

        export JULIA_DEPOT_PATH="${CI_BUILD_DIR}/depot/cpu"
        export JULIA_CUDA_USE_BINARYBUILDER=false
        export JULIA_MPI_BINARY=system

        export OMPI_MCA_btl="self,tcp"
        
        export CLIMATEMACHINE_SETTINGS_OUTPUT_DIR="${CI_BUILD_DIR}/output/${BUILDKITE_STEP_KEY}"
        ;;

    gpu)
        echo "--- gpu env configuration"
        module load julia/${JULIA_VERSION:=1.4.2}
        module load cuda/10.0 openmpi/4.0.3_cuda-10.0 hdf5/1.10.1 netcdf-c/4.6.1

        export BUILDKITE_BUILD_CHECKOUT_PATH=${CI_BUILD_DIR}

        export JULIA_DEPOT_PATH="${CI_BUILD_DIR}/depot/gpu"
        export JULIA_CUDA_USE_BINARYBUILDER=false
        export JULIA_MPI_BINARY=system

        export OMPI_MCA_btl="self,tcp"

        export CLIMATEMACHINE_SETTINGS_OUTPUT_DIR="${CI_BUILD_DIR}/output/${BUILDKITE_STEP_KEY}"

        echo "--- gpu device configuration"
        nvidia-smi -q
        ;;

    gpu-test)
        echo "--- gpu test env configuration"
        module load julia/${JULIA_VERSION:=1.5.1}
        module load cuda/10.2 openmpi/4.0.4_cuda-10.2 hdf5/1.10.1 netcdf-c/4.6.1

        export BUILDKITE_BUILD_CHECKOUT_PATH=${CI_BUILD_DIR}

        export JULIA_DEPOT_PATH="${CI_BUILD_DIR}/depot/gpu"
        export JULIA_CUDA_USE_BINARYBUILDER=false
        export JULIA_MPI_BINARY=system

        export OMPI_MCA_btl="self,tcp"
        
        export CLIMATEMACHINE_SETTINGS_OUTPUT_DIR="${CI_BUILD_DIR}/output/${BUILDKITE_STEP_KEY}"

        echo "--- gpu test device configuration"
        nvidia-smi -q
        ;;

    *)
        echo "agent config must init, cpu or gpu"
        ;;

esac

set +v
