#!/bin/bash

# The `post-command` hook will run after the bootstrap script has run your
# build commands

set -euo pipefail # exit on failure or unset variable
set -v

case "${BUILDKITE_AGENT_META_DATA_CONFIG}" in
    # standard configurations
    cpu|cpu-test|gpu|gpu-test)
        echo "--- Slurm efficiency job output"
        # sleep for a bit (jobs resources are sampled at a specified interval)
        # sleep 30s
        # seff ${SLURM_JOB_ID}
        ;;
esac

set +v
