#!/bin/bash

# The `pre-exit` hook will run just before your build job finishes

# Note that as the script is sourced not run directly, the shebang line will be ignored
# See https://buildkite.com/docs/agent/v3/hooks#creating-hook-scripts

set -euo pipefail # exit on failure or unset variable

df -h /tmp/

# Remove tempdir (skip if TMPDIR was never set or is just /tmp)
if [ -n "${TMPDIR:-}" ] && [ "$TMPDIR" != "/tmp" ]; then
    case "$BUILDKITE_AGENT_META_DATA_QUEUE" in
        "central")
            srun --ntasks-per-node=1 --ntasks="${SLURM_JOB_NUM_NODES}" rm -rf "$TMPDIR";
            ;;
        "clima")
            rm -rf "$TMPDIR"
            ;;
        "derecho")
            pbsdsh -- rm -rf "$TMPDIR"
            ;;
        "gcp")
            srun --ntasks-per-node=1 --ntasks="${SLURM_JOB_NUM_NODES}" rm -rf "$TMPDIR";
            ;;
        "test")
            rm -rf "$TMPDIR"
            ;;
    esac
fi
