#!/bin/bash

# The `pre-command` hook will run just before your build command runs

set -euo pipefail # exit on failure or unset variable
set -v

# override curl options for Pkg artifacts
# export CURL_HOME="$(dirname "$BUILDKITE_BUILD_CHECKOUT_PATH")"
# printf -- "--retry 8\n" > "$CURL_HOME/.curlrc"

# Ensure that the output folder can be seen by the everyone in the hpc_esm group
# Since the output folder is in /scratch, we must change this setting every time
# scratch is purged
case "$BUILDKITE_AGENT_META_DATA_QUEUE" in
    "central")
        chgrp hpc_esm $BUILDKITE_BUILD_PATH
        chmod g+s $BUILDKITE_BUILD_PATH
        ;;
    "gcp")
        chmod 755 $BUILDKITE_BUILD_PATH
        ;;
esac

set +v
